name: Sync Storybook

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  sync-storybook-with-claude-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            Keep the stories in the storybook exahustive of their state.
            Check that the components in the storybook cover all their possible states.